### ISSUE TITLE
App id.bmri.livin Force Closed When Using Cara Kernel MS3 and Above

### ISSUE THREAD

**Issue by nalakawula** [FlopKernel-Series/flop_trinket-mi_kernel#3]
Hi, thank you for the nice kernel.

I am very curious why [this app](https://play.google.com/store/apps/details?id=id.bmri.livin) is force close when using CaraKernel MS3 and later. That was not happen when using CaraKernel MS2.

I try to read the commit log, but still clueless.

Thanks

**Comment by Flopster101** [comment]
Hey! Sorry for the late reply.
If you want me to investigate this you should provide a log of the app crash (most ROMs will let you copy a link to the crash log when it force closes).

Since I'm on my way to releasing MS8 in a moment, I will appreciate if you could test on that version. I will not accept testing on versions older than MS6 because of huge changes in the base kernel.

**Comment by nalakawula** [comment]
Log with MS8:
```
05-29 07:46:20.124   929   929 E perfetto: probes_producer.cc:176  Failed to create data source 'linux.ftrace'
05-29 07:46:20.124   929   929 E perfetto: probes_producer.cc:191  Data source id=9 not found
05-29 07:46:20.862   540   540 E Layer   : [Surface(name=Task=438)/@0xf0c4ed - animation-leash#0] No local sync point found
05-29 07:46:20.862   540   540 E Layer   : [Surface(name=Task=1)/@0x2b1641d - animation-leash#0] No local sync point found
05-29 07:46:21.622 11368 11368 E AndroidRuntime: FATAL EXCEPTION: main
05-29 07:46:21.622 11368 11368 E AndroidRuntime: Process: id.bmri.livin, PID: 11368
05-29 07:46:21.622 11368 11368 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{id.bmri.livin/com.bankmandiri.md.presentation.ui.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Number.intValue()' on a null object reference
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3432)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3596)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7700)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:959)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Number.intValue()' on a null object reference
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at o.ucl.c(Unknown Source:20)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at o.uco.b(:1800)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at o.uco.b(:1514)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at com.bankmandiri.md.presentation.ui.MainActivity.onCreate(Unknown Source:2768)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7994)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7978)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1358)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3405)
05-29 07:46:21.622 11368 11368 E AndroidRuntime: 	... 11 more
05-29 07:46:22.874 12007 12007 E id.bmri.livin: Not starting debugger since process cannot load the jdwp agent.
```

**Comment by nalakawula** [comment]
Anothe log from /proc/kmesg
```
<36>[ 1366.815647] type=1400 audit(1685351087.209:350): avc: denied { read } for comm="id.bmri.livin" name="filesystems" dev="proc" ino=4026532148 scontext=u:r:untrusted_app:s0:c184,c256,c512,c768 tcontext=u:object_r:proc_filesystems:s0 tclass=file permissive=0 app=id.bmri.livin
<36>[ 1367.664496] type=1400 audit(1685351088.055:351): avc: denied { read } for comm="id.bmri.livin" name="policy" dev="selinuxfs" ino=20 scontext=u:r:untrusted_app:s0:c184,c256,c512,c768 tcontext=u:object_r:selinuxfs:s0 tclass=file permissive=0 app=id.bmri.livin
```

**Comment by nalakawula** [comment]
I solved the selinux issue by using `magiskpolicy` and here the next log:
```
05-30 07:35:23.399  1262  3492 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=id.bmri.livin/com.bankmandiri.md.presentation.ui.MainActivity bnds=[841,1756][1043,2091]} from uid 10154
05-30 07:35:23.439  1262  1348 I ActivityManager: Start proc 9585:id.bmri.livin/u0a184 for pre-top-activity {id.bmri.livin/com.bankmandiri.md.presentation.ui.MainActivity}
05-30 07:35:23.466  9585  9585 E id.bmri.livin: Not starting debugger since process cannot load the jdwp agent. 
05-30 07:35:23.492  9585  9585 I id.bmri.livin: The ClassLoaderContext is a special shared library.             
05-30 07:35:23.601  9585 12469 W id.bmri.livin: ClassLoaderContext classpath element mismatch. expected=/data/app/liEra2gzvJNiws0srtT3aQ==/com.android.vending-tJlkOKb1_Mf1-eYsYRwV-g==/base.apk, found=/data/app/yb4igc-CJTlliV2XiwchcQ==/id.bmri.livin-AJaApVyDwbt_NcV6l8FnfQ==/base.apk (DLC[];PCL[/data/app/liEra2gzvJNiws0srtT3aQ==/com.android.vending-tJlkOKb1_Mf1-eYsYRwV-g==/base.apk*2178300252:/data/app/liEra2gzvJNiws0srtT3aQ==/com.android.vending-tJlkOKb1_Mf1-eYsYRwV-g==/base.apk!classes2.dex*800248440:/data/app/liEra2gzvJNiws0srtT3aQ==/com.android.vending-tJlkOKb1_Mf1-eYsYRwV-g==/base.apk!classes3.dex*883352456:/data/app/liEra2gzvJNiws0srtT3aQ==/com.android.vending-tJlkOKb1_Mf1-eYsYRwV-g==/base.apk!classes4.dex*1248686895:/data/app/liEra2gzvJNiws0srtT3aQ==/com.android.vending-tJlkOKb1_Mf1-eYsYRwV-g==/base.apk!classes5.dex*1995213805:/data/app/liEra2gzvJNiws0srtT3aQ==/com.android.vending-tJlkOKb1_Mf1-eYsYRwV-g==/base.apk!classes6.dex*1575363946]{PCL[/system/framework/org.apache.http.legacy.jar*181645345]} | DLC[];PCL[/data/app/yb4igc-CJTlliV2XiwchcQ==/id.bmri.livin-AJaApVyDwbt_NcV6l8FnfQ==/base.apk*3016608949:/data/app/yb4igc-CJTlliV2XiwchcQ==/id.bmri.livin-AJaApVyDwbt_NcV6l8FnfQ==/base.apk!classes2.dex*1791531087:/data/app/yb4igc-CJTlliV2XiwchcQ==/id.bmri.livin-AJaApVyDwbt_NcV6l8FnfQ==/base.apk!classes3.dex*2567170869:/data/app/yb4igc-CJTlliV2XiwchcQ==/id.bmri.livin-AJaApVyDwbt_NcV6l8FnfQ==/base.apk!classes4.dex*1991516562:/data/app/yb4igc-CJTlliV2XiwchcQ==/id.bmri.livin-AJaApVyDwbt_NcV6l8FnfQ==/base.apk!classes5.dex*4049552321:/data/app/yb4igc-CJTlliV2XiwchcQ==/id.bmri.livin-AJaApVyDwbt_NcV6l8FnfQ==/base.apk!classes6.dex*2883319669]{PCL[/system/framework/org.apache.http.legacy.jar*181645345]})
05-30 07:35:23.602  9585 12469 W id.bmri.livin: Found duplicate classes, falling back to extracting from APK : /data/user_de/0/com.google.android.gms/app_chimera/m/00000027/MeasurementDynamite.apk
05-30 07:35:23.603  9585 12469 W id.bmri.livin: NOTE: This wastes RAM and hurts startup performance.            
05-30 07:35:23.603  9585 12469 W id.bmri.livin: Found duplicated class when checking oat files: 'Landroidx/annotation/Keep;' in /data/app/~~yb4igc-CJTlliV2XiwchcQ==/id.bmri.livin-AJaApVyDwbt_NcV6l8FnfQ==/base.apk and /data/user_de/0/com.google.android.gms/app_chimera/m/00000027/MeasurementDynamite.apk
05-30 07:35:23.608  9585  9585 I TetheringManager: registerTetheringEventCallback:id.bmri.livin                 
05-30 07:35:23.723  9585 12498 I FA      :   adb shell setprop debug.firebase.analytics.app id.bmri.livin       
05-30 07:35:25.048  9585  9585 E AndroidRuntime: Process: id.bmri.livin, PID: 9585
05-30 07:35:25.048  9585  9585 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{id.bmri.livin/com.bankmandiri.md.presentation.ui.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Number.intValue()' on a null object reference
05-30 07:35:25.188  1262  7359 W ActivityTaskManager:   Force finishing activity id.bmri.livin/com.bankmandiri.md.presentation.ui.MainActivity
05-30 07:35:25.258  1262  8027 I ActivityManager: Process id.bmri.livin (pid 9585) has died: fg  TOP            
05-30 07:35:25.689  1262  1335 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{a125618 u0 id.bmri.livin/com.bankmandiri.md.presentation.ui.MainActivity t-1 f}}
```

**Comment by Flopster101** [comment]
I'm honestly at a total loss with this. Can't seem to find a cause for the problem.

> java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Number.intValue()' on a null object reference

That's too generic of an error, and neither the logs or dmesg point to anything related to the kernel. The SELinux denials also 
seem to be normal stuff.

**Comment by rdxzv** [comment]
Hi @Flopster101 did you find any way to fix that? I'm also facing that in a different device

**Comment by nalakawula** [comment]
Hi guys, coming back here to share some reference for you. QuickSilver kernel also have same issue and they already fix this issue by [this commit](https://github.com/DerpFest-ginkgo/kernel_xiaomi_ginkgo/commit/dce6057772781f80d343e6cd3db6dc26bb2d6ba7).

Thanks

**Comment by rdxzv** [comment]
Oh, Hi! Yeah I'm the author of that :)

**Comment by Flopster101** [comment]
The fix had already been implemented back in MS10, I just forgot to close the issue. Thank you @rdxzv!!
